/** @author liuxing.li — deterministic JSON -> TypeScript/CSS token generator. */
import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const root = fileURLToPath(new URL('../', import.meta.url));
const sourcePath = resolve(root, 'assets/ops-pilot.tokens.json');
const hex = /^#[\da-f]{6}$/i;
const identifier = /^[a-z][a-zA-Z0-9]*$/;

/** Convert a camelCase token key to a stable CSS custom-property segment. */
export function kebab(key) {
  return key.replace(/[A-Z]+/g, (match) => `-${match.toLowerCase()}`);
}

/** Validate both theme key sets and reject malformed leaf values early. */
export function validateTokens(tokens) {
  if (tokens.version !== '2.0.0' || !tokens.name) throw new Error('Invalid token metadata');
  const modes = Object.keys(tokens.color ?? {}).sort();
  if (modes.join() !== 'dark,light') throw new Error('Expected light and dark themes');
  const keys = Object.keys(tokens.color.light).sort();
  if (keys.join() !== Object.keys(tokens.color.dark).sort().join()) {
    throw new Error('Light/dark token keys differ');
  }
  for (const required of ['canvas', 'surface', 'text', 'primary', 'onPrimary', 'focus', 'controlBorder']) {
    if (!keys.includes(required)) throw new Error(`Missing color: ${required}`);
  }
  for (const mode of modes) {
    for (const [key, value] of Object.entries(tokens.color[mode])) {
      if (!identifier.test(key) || typeof value !== 'string' || !hex.test(value)) {
        throw new Error(`Invalid color: ${mode}.${key}`);
      }
    }
  }
  for (const group of ['space', 'radius', 'layout', 'typography', 'motion', 'shadow', 'density']) {
    if (!tokens[group] || typeof tokens[group] !== 'object') throw new Error(`Missing group: ${group}`);
  }
  if (Object.keys(tokens.density).sort().join() !== 'comfortable,compact') {
    throw new Error('Expected comfortable and compact densities');
  }
  const visit = (object, path) => {
    for (const [key, value] of Object.entries(object)) {
      if (!identifier.test(key)) throw new Error(`Invalid key: ${path}.${key}`);
      if (typeof value === 'object' && value !== null) visit(value, `${path}.${key}`);
      else if (typeof value === 'number') {
        if (!Number.isFinite(value) || value < 0) throw new Error(`Invalid number: ${path}.${key}`);
      } else if (typeof value !== 'string' || /[;{}\n\r]/.test(value)) {
        throw new Error(`Unsafe CSS value: ${path}.${key}`);
      }
    }
  };
  for (const group of ['space', 'radius', 'layout', 'typography', 'motion', 'shadow', 'density']) {
    visit(tokens[group], group);
  }
  return tokens;
}

/** Read the sole editable token source. Returns a validated plain object. */
export async function loadTokens() {
  return validateTokens(JSON.parse(await readFile(sourcePath, 'utf8')));
}

function declarations(values, prefix = '', unit = '') {
  return Object.entries(values).map(([key, value]) => {
    const suffix = typeof value === 'number' ? unit : '';
    return `  --ops-${prefix}${kebab(key)}: ${value}${suffix};`;
  }).join('\n');
}

/** Build the complete generated artifact map without writing to disk. */
export function artifacts(tokens) {
  validateTokens(tokens);
  const t = tokens.typography;
  const css = [
    '/* Generated by scripts/tokens.mjs. Edit ops-pilot.tokens.json instead. */',
    ':root {',
    declarations(tokens.space, 'space-', 'px'),
    declarations(tokens.radius, 'radius-', 'px'),
    declarations(tokens.layout, 'layout-', 'px'),
    declarations({ fontFamily: t.fontFamily, fontFamilyCode: t.fontFamilyCode }),
    declarations(t.fontSize, 'font-size-', 'px'),
    declarations(t.lineHeight, 'line-height-', 'px'),
    declarations(t.weight, 'weight-'),
    declarations(tokens.motion, 'motion-', 'ms'),
    declarations(tokens.shadow, 'shadow-'),
    '}',
    ...Object.entries(tokens.color).map(([mode, values]) => [
      mode === 'light' ? ':root, [data-ops-theme="light"] {' : '[data-ops-theme="dark"] {',
      `  color-scheme: ${mode};`, declarations(values), '}',
    ].join('\n')),
    ...Object.entries(tokens.density).map(([density, values]) => [
      density === 'comfortable' ? ':root, [data-ops-density="comfortable"] {' : '[data-ops-density="compact"] {',
      declarations(values, '', 'px'), '}',
    ].join('\n')),
    '',
  ].join('\n');
  const ts = [
    '// Generated by scripts/tokens.mjs. Edit ops-pilot.tokens.json instead.',
    `export const opsTokens = ${JSON.stringify(tokens, null, 2)} as const;`,
    '',
    'export type OpsMode = keyof typeof opsTokens.color;',
    'export type OpsDensity = keyof typeof opsTokens.density;',
    '',
  ].join('\n');
  return new Map([
    ['assets/design-tokens.ts', ts],
    ['assets/ops-pilot.tokens.css', css],
  ]);
}

/** CLI: no arguments generates; --check validates drift; --help prints usage. */
export async function main(args = process.argv.slice(2)) {
  if (args.length > 1 || (args.length === 1 && !['--check', '--help'].includes(args[0]))) {
    throw new Error('Usage: node scripts/tokens.mjs [--check | --help]');
  }
  if (args[0] === '--help') {
    console.info('Usage: node scripts/tokens.mjs [--check | --help]');
    return;
  }
  const outputs = artifacts(await loadTokens());
  for (const [path, content] of outputs) {
    const target = resolve(root, path);
    if (args[0] === '--check') {
      const existing = await readFile(target, 'utf8').catch(() => '');
      if (existing !== content) throw new Error(`Generated file drift: ${path}`);
    } else await writeFile(target, content, 'utf8');
  }
  console.info(`${args[0] === '--check' ? 'Checked' : 'Generated'} ${outputs.size} token artifacts`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  });
}
